//
// Created by biore on 12/8/2022.
//

#ifndef LAB4MEMORYALLOCATOR_FSACONSTANTS_H
#define LAB4MEMORYALLOCATOR_FSACONSTANTS_H

static const int NEXT_FREE_LIST_ITEM_NOT_ASSIGNED = -1;
static const int NEXT_FREE_LIST_ITEM_IS_OUT_OF_RANGE = -2;

#endif //LAB4MEMORYALLOCATOR_FSACONSTANTS_H
