//
// Created by biore on 12/10/2022.
//

#ifndef LAB4MEMORYALLOCATOR_COMMONBLOCKMETADATA_H
#define LAB4MEMORYALLOCATOR_COMMONBLOCKMETADATA_H


struct CommonBlockMetaData {

};


#endif //LAB4MEMORYALLOCATOR_COMMONBLOCKMETADATA_H
