//
// Created by biore on 12/8/2022.
//

#ifndef LAB4MEMORYALLOCATOR_MEMORYALLOCATORCONSTANTS_H
#define LAB4MEMORYALLOCATOR_MEMORYALLOCATORCONSTANTS_H

// FSA constants
static const int NEXT_FREE_LIST_ITEM_NOT_ASSIGNED = -1;
static const int NEXT_FREE_LIST_ITEM_IS_OUT_OF_RANGE = -2;
static const int MIN_FSA_BLOCK_SIZE = 16;

// Coalesce allocator constants
static const int MAX_COALESCE_REQUEST_SIZE = 1024 * 1024 * 10;

#endif //LAB4MEMORYALLOCATOR_MEMORYALLOCATORCONSTANTS_H
